name: CI/CD Pipeline
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Copies the repository code into runner's env for the subsequent steps to access
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test
  
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build test Docker image
        run: docker build -t sanyamgupta/docker-test-demo -f Dockerfile.dev .
      
      - name: Run tests in Docker
        run: docker run -e CI=true sanyamgupta/docker-test-demo npm test        

      - name: Build prod Docker image
        run: docker build -t sanyamgupta23/docker-prod-aws .
      
      - name: Push prod Docker image
        run: docker push sanyamgupta23/docker-prod-aws

      - name: Generate deployment package
        run: zip -r deploy.zip Dockerrun.aws.json -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-aws-demo
          environment_name: Docker-aws-demo-env
          version_label: ${{ github.sha }}
          existing_bucket_name: elasticbeanstalk-us-east-1-024848469382
          region: us-east-1
          deployment_package: deploy.zip

      - name: Deployed!
        run: echo App deployed to ELB