name: CI/CD Pipeline
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Copies the repository code into runner's env for the subsequent steps to access
      - name: Checkout code 
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run test